apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontcache.fullname" . }}-minio
  labels:
    {{- include "frontcache.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: api
      protocol: TCP
      name: api
    - port: 9001
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "frontcache.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
