apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "frontcache.fullname" . }}
  labels:
    {{- include "frontcache.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
